name: Run YouTube to Instagram bot 4x daily

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'  # Runs at 00:00, 06:00, 12:00, 18:00 UTC every day
  workflow_dispatch:  # Allows you to trigger manually if needed

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        run: |
          python main.py
